version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: price_tracker
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json

  postgresql:
    image: postgres:14.5 
    container_name: price_tracker_postgres
    restart: unless-stopped 
    volumes:
      - ./article.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    # healthcheck:
    #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #   timeout: 5s
    #   retries: 10

  headless-shell:
    image: chromedp/headless-shell:105.0.5195.127
    init: true
    container_name: headless_chrome_shell
    restart: unless-stopped
    ports:
      - 9222:9222